apiVersion: apps/v1
kind: Deployment
metadata:
  name: fidelity-app
  namespace: fidelity
spec:
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  selector:
    matchLabels:
      app: fidelity
  template:
    metadata:
      labels:
        app: fidelity
    spec:
      containers:
        - name: fidelity
          image: fidelity:20250525-1629
          imagePullPolicy: Never
          command: ["./fidelity"]
          args: ["--configpath", "/app/config/local_env.yaml"]
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 2
            periodSeconds: 5
