apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
  namespace: fidelity
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
      - name: postgres
        image: postgres:15.2-alpine
        env:
        - name: POSTGRES_USER
          value: "fidelity"          # valor fixo aqui
        - name: POSTGRES_DB
          value: "fidelity"          # valor fixo aqui
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: postgres-secret
              key: POSTGRES_PASSWORD
        volumeMounts:
        - mountPath: /var/lib/postgresql/data
          name: postgres-storage
        ports:
        - containerPort: 5432
      volumes:
        - name: postgres-storage
          persistentVolumeClaim:
            claimName: postgres-pvc
