apiVersion: v1
kind: Service
metadata:
  name: fidelity-service
spec:
  type: NodePort
  selector:
    app: fidelity
  ports:
    - name: http
      protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 30080
