server:
  host: localhost
  port: 9901


platform: "dev-env"
database_type: "postgres"

postgres:
  host: "localhost"
  port: "6543"
  database: "fidelity"
  username: "postgres"
  password: "postgres"
  sslmode: "disable" 

log:
  level: "debug"