app:
  port: 8080
  base_url: "http://192.168.0.100:8080"
  env: "local"
  secret_key: "supersecretkey"

database:
  type: "postgres"
  host: "localhost"
  port: 5432
  user: "fidelity_user"
  password: "pass"
  name: "fidelity"
  sslmode: "disable"

log:
  level: "debug"
