server:
  host: 0.0.0.0
  port: 8080

platform: "local-env"
database_type: "postgres"

postgres:
  host: postgres.database.svc.cluster.local
  port: "5432"
  database: "fidelity_db"
  username: "fidelity"
  password: "suaSenhaSeguraAqui"
  sslmode: "disable"

log:
  level: "debug"
